### ISSUE TITLE
Fatal error when failing to connect to a Chromecast

### ISSUE THREAD

**Issue by PeterRob** [willemstuursma/castblock-php#3]
I suspect this error is thrown when I cast audio to a Chromecast audio:

```
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: PHP Warning:  Undefined array key "identifier" in phar:///usr/bin/castblock-php.phar/src/ValueObjects/Status.php on line 30
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: PHP Fatal error:  Uncaught TypeError: WillemStuursma\CastBlock\SponsorBlockApi::getSegments(): Argument #1 ($videoId) must be of type string, null given, called in phar:///usr/bin/castblock-php.phar/src/Commands/RunCommand.php on line 125 and defined in phar:///usr/bin/castblock-php.phar/src/SponsorBlockApi.php:54
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: Stack trace:
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: #0 phar:///usr/bin/castblock-php.phar/src/Commands/RunCommand.php(125): WillemStuursma\CastBlock\SponsorBlockApi->getSegments()
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: #1 phar:///usr/bin/castblock-php.phar/src/Commands/RunCommand.php(101): WillemStuursma\CastBlock\Commands\RunCommand->skipSponsors()
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: #2 phar:///usr/bin/castblock-php.phar/vendor/symfony/console/Command/Command.php(256): WillemStuursma\CastBlock\Commands\RunCommand->execute()
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: #3 phar:///usr/bin/castblock-php.phar/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: #4 phar:///usr/bin/castblock-php.phar/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: #5 phar:///usr/bin/castblock-php.phar/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: #6 phar:///usr/bin/castblock-php.phar/bin/castblock-php(14): Symfony\Component\Console\Application->run()
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: #7 /usr/bin/castblock-php.phar(14): require('...')
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]: #8 {main}
Sep 26 08:35:27 hc2-1 castblock-php.phar[5850]:   thrown in phar:///usr/bin/castblock-php.phar/src/SponsorBlockApi.php on line 54
Sep 26 08:35:27 hc2-1 systemd[1]: sponsorblockcast.service: Main process exited, code=exited, status=255/EXCEPTION
Sep 26 08:35:27 hc2-1 systemd[1]: sponsorblockcast.service: Failed with result 'exit-code'.
```

**Comment by willemstuursma** [comment]
Hi @PeterRob, thanks for reporting. 

Could you share the steps to reproduce this problem? Unfortunately I don't have a Chromecast Audio to test with. 

Please be elaborate, I don't know anything about your set up.

**Comment by PeterRob** [comment]
Thanks for the quick reply!

Castblock-php running on an ARMhf device / Ubuntu 20.04

peter@hc2-1:~$ go-chromecast --version
go-chromecast v0.2.10 (59e712c) 2021-08-08T15:27:19Z

Running from the console:

```
peter@hc2-1:~$ /usr/bin/castblock-php.phar -vvv     

Box Requirements Checker
========================

> Using PHP 8.0.11
> PHP is using the following php.ini file:
  /etc/php/8.0/cli/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.1 || ^8.0" or greater.
  ✔ The application requires the extension "zlib".
  ✔ The application requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "myclabs/php-enum" requires the extension "json".
  
                                                                                                                                                                    
 [OK] Your system is ready to run the application.                                                                                                                  
                                                                                                                                                                    

[debug] Starting CastBlock PHP...
[info] Found Chromecast Audio "Living Room speaker" at 192.168.131.106:8009.
[info] Found Google Cast Group "Audio" at 192.168.131.106:42857.
[debug] Chromecast Audio Living Room speaker is not playing Youtube.
[debug] Google Cast Group Audio is not playing Youtube.

In Process.php line 267:
                                                                                                                                              
  [Symfony\Component\Process\Exception\ProcessFailedException]                                                                                
  The command "'/usr/bin/go-chromecast' 'status' '--debug' '--addr' '192.168.131.106' '--port' '8009'" failed.                                
                                                                                                                                              
  Exit Code: 1(General error)                                                                                                                 
                                                                                                                                              
  Working directory: /home/peter                                                                                                              
                                                                                                                                              
  Output:                                                                                                                                     
  ================                                                                                                                            
  error: unable to get cast application: unable to connect to chromecast at '192.168.131.106:8009': tls: DialWithDialer timed out  
                                                                                                                                              
                                                                                                                                              
  Error Output:                                                                                                                               
  ================                                                                                                                            
                                                                                                                                              

Exception trace:
  at phar:///usr/bin/castblock-php.phar/vendor/symfony/process/Process.php:267
 Symfony\Component\Process\Process->mustRun() at phar:///usr/bin/castblock-php.phar/src/ChromeCastConnector.php:51
 WillemStuursma\CastBlock\ChromeCastConnector->getStatus() at phar:///usr/bin/castblock-php.phar/src/Commands/RunCommand.php:238
 WillemStuursma\CastBlock\Commands\RunCommand->getChromeCastStatus() at phar:///usr/bin/castblock-php.phar/src/Commands/RunCommand.php:117
 WillemStuursma\CastBlock\Commands\RunCommand->skipSponsors() at phar:///usr/bin/castblock-php.phar/src/Commands/RunCommand.php:101
 WillemStuursma\CastBlock\Commands\RunCommand->execute() at phar:///usr/bin/castblock-php.phar/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/castblock-php.phar/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/castblock-php.phar/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/castblock-php.phar/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at phar:///usr/bin/castblock-php.phar/bin/castblock-php:14
 require() at /usr/bin/castblock-php.phar:14

app:run [-c|--category CATEGORY]

```

**Comment by willemstuursma** [comment]
Hi @PeterRob.

Would you mind running `go-chromecast status --debug` while your Chromecast Audio is playing Youtube, and post the output here?

**Comment by PeterRob** [comment]
```
root@hc2-1:/home/peter# go-chromecast status --device-name "Living Room speaker"
Chrome Audio Mirroring (PLAYING), unknown, time remaining=0s/0s, volume=0.54, muted=false
```

**Comment by willemstuursma** [comment]
Thanks @PeterRob. Jus to confirm, this was while streaming some Youtube right?

**Comment by PeterRob** [comment]
Yes streaming Youtube video to a Chromecast audio.

**Comment by willemstuursma** [comment]
Sorry, I only now noticed you missed the `--debug` flag which castblock uses to get more precise info on the position of what we are playing. Could you try again with the flag added?

**Comment by PeterRob** [comment]
@willemstuursma  - with the full text 

```
peter@hc2-1:~$` go-chromecast status --debug
Found 4 cast dns entries, select one:
1) device="Google Cast Group" device_name="Audio" address="192.168.131.106:42857" uuid="8986e66a-dab0-4324-b778-03ee83da6eb8"
2) device="Chromecast" device_name="Bedroom TV" address="192.168.131.107:8009" uuid="a6015b2ec51f7f3bdba7b7c515d22434"
3) device="Chromecast" device_name="Living Room TV" address="192.168.131.104:8009" uuid="195b87ecb400bc8f179732817effef88"
4) device="Chromecast Audio" device_name="Living Room speaker" address="192.168.131.106:8009" uuid="04ecf49340207aaa4823175666192ae4"
Enter selection: 4
using device name=Living Room speaker addr=192.168.131.106 port=8009 uuid=04ecf49340207aaa4823175666192ae4
Chrome Audio Mirroring (PLAYING), unknown, time remaining=0s/0s, volume=0.54, muted=false
```

**Comment by willemstuursma** [comment]
There seem to be various issues at play.

I've resolved the fatal error when failing to connect to a Chromecast device. And added improved output if there is no identifier of the Youtube video is found while a Chromecast playing Youtube. 

Could you try the new version and if there are any further problems let me know.
